"""
Security validation tests generated by the Valyu security scanner (kevin).
These tests verify that internal implementation details are not exposed
in the public SDK response types.
"""

import re
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_kevin_20260401_001():
    """SDK response types must not expose internal storage identifiers s3_key and api_key_id.

    Severity: high
    Category: injection
    Finding: DeliverableResult.s3_key and DeepResearchBatch.api_key_id are internal
    storage identifiers that must not be returned in public SDK response shapes.
    """
    types_file = os.path.join(REPO_ROOT, "src", "types.ts")
    with open(types_file) as f:
        content = f.read()

    # Verify s3_key is not present in DeliverableResult
    deliverable_match = re.search(
        r"export interface DeliverableResult \{([^}]+)\}", content, re.DOTALL
    )
    assert deliverable_match, "DeliverableResult interface not found in src/types.ts"
    deliverable_body = deliverable_match.group(1)
    assert "s3_key" not in deliverable_body, (
        "Security vulnerability CVE-equivalent kevin-20260401-001: "
        "DeliverableResult exposes s3_key (internal S3 storage identifier) "
        "in public SDK response type"
    )

    # Verify api_key_id is not present in DeepResearchBatch
    batch_match = re.search(
        r"export interface DeepResearchBatch \{([^}]+)\}", content, re.DOTALL
    )
    assert batch_match, "DeepResearchBatch interface not found in src/types.ts"
    batch_body = batch_match.group(1)
    assert "api_key_id" not in batch_body, (
        "Security vulnerability CVE-equivalent kevin-20260401-001: "
        "DeepResearchBatch exposes api_key_id (internal API key identifier) "
        "in public SDK response type"
    )
