"""
Security finding validation tests.
Generated by Kevin (security scan agent).
"""

import re
import os


def test_kevin_20260402_002():
    """
    Security check: DeepResearchBatch must not expose internal organisational
    identifiers (organisation_id, api_key_id, credit_id).

    These fields are server-side internal IDs that have no meaning to SDK
    consumers and leak infrastructure details. Exposing them in the public
    type also allows clients to inject these fields into forged or replayed
    requests, enabling cross-organisation access patterns.

    Severity: high
    Category: injection
    File: src/types.ts (DeepResearchBatch)
    """
    types_path = os.path.join(os.path.dirname(__file__), "..", "src", "types.ts")
    with open(types_path) as f:
        content = f.read()

    # Extract the DeepResearchBatch interface body
    match = re.search(
        r"export interface DeepResearchBatch \{(.+?)\n\}",
        content,
        re.DOTALL,
    )
    assert match, "DeepResearchBatch interface not found in src/types.ts"

    batch_body = match.group(1)

    # Internal server-side fields must not be present in the public SDK type
    assert "organisation_id" not in batch_body, (
        "DeepResearchBatch must not expose internal field 'organisation_id' - "
        "leaks organisational infrastructure details"
    )
    assert "api_key_id" not in batch_body, (
        "DeepResearchBatch must not expose internal field 'api_key_id' - "
        "enables API key enumeration and injection"
    )
    assert "credit_id" not in batch_body, (
        "DeepResearchBatch must not expose internal field 'credit_id' - "
        "leaks internal billing/credit identifiers"
    )
